UGV:
  - msg_type: "robotnik_msgs/BatteryStatus"
    ros_topic: "/robot/battery_estimator/data"
    kafka_topic: "ugv.battery.status"
  - msg_type: "sensor_msgs/NavSatFix"
    ros_topic: "/robot/gps/fix"
    kafka_topic: "ugv.gps.fix"
  - msg_type: "robotnik_msgs/State"
    ros_topic: "/robot/robot_local_control/RobotStatusComponent/state"
    kafka_topic: "ugv.state"
  - msg_type: "std_msgs/String"
    ros_topic: "/hlp/state"
    kafka_topic: "hlp.state"
